### ISSUE TITLE
When I open the subscription dashboard as SYE domain I get an unhandled error

### ISSUE THREAD

**Issue by nlesa** [RHEAGROUP/COMET-WEB-Community-Edition#132]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I open the model as SYE clicking on the subscription dashboard throws an unhandled error. 

### Steps to Reproduce
1. Login to COMET web app
2. Open a model as SYE
3. Click on subscription dashboard

### Logs
   - [] I have attached a log file or included the relevant section in this issue  

```
 blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_NullReferenceException
System.NullReferenceException: Arg_NullReferenceException
   at COMETwebapp.Components.SubscriptionDashboard.SubscribedTable.<>c__DisplayClass15_0.<GetViewModelSubscribedParameters>b__1(ParameterSubscriptionValueSet parameterSubscriptionValueSet)
   at System.Collections.Generic.List`1[[CDP4Common.EngineeringModelData.ParameterSubscriptionValueSet, CDP4Common, Version=8.1.0.0, Culture=neutral, PublicKeyToken=null]].ForEach(Action`1 )
   at COMETwebapp.Components.SubscriptionDashboard.SubscribedTable.<GetViewModelSubscribedParameters>b__15_0(ParameterSubscription subscribedparameter)
   at System.Collections.Generic.List`1[[CDP4Common.EngineeringModelData.ParameterSubscription, CDP4Common, Version=8.1.0.0, Culture=neutral, PublicKeyToken=null]].ForEach(Action`1 )
   at COMETwebapp.Components.SubscriptionDashboard.SubscribedTable.GetViewModelSubscribedParameters()
   at COMETwebapp.Components.SubscriptionDashboard.SubscribedTable.LoadData()
   at COMETwebapp.Components.SubscriptionDashboard.SubscribedTable.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync() 
```
  
### System Configuration

- COMET version:
  - [ ] COMET-WEB: 0.16.0
  - [ ] Other: 
- Web Services:
  - [ ] COMET Web Services version:

**Comment by samatrhea** [comment]
currently refactoring which should solve this
