### ISSUE TITLE
Add a login page

### ISSUE THREAD

**Issue by justineatrhea** [RHEAGROUP/COMET-WEB-Community-Edition#2]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-WEB
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-WEB-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Use of ISession to add SDK to the app.

### Steps to Reproduce
NA

### Logs
 NA

### System Configuration
NA

**Comment by nlesa** [comment]
## Description: 
I should be able to login and if I cannot it should tell me why. 
When logging in with an invalid source the login fails and continuously loads without a clear warning that something is wrong. An error message does appear at the bottom of the screen but this is greyed out and easily missed. 
...
## Steps to reproduce: 1. Login with incorrect source, correct username and password
...
## Test data / logs:
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
blazor.webassembly.js:1 

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> System.Runtime.InteropServices.JavaScript.JSException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage , CancellationToken )
   Exception_EndOfInnerExceptionStack
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at CDP4ServicesDal.CdpServicesDal.Open(Credentials credentials, CancellationToken cancellationToken)
   at CDP4Dal.Session.Open(Boolean activeMessageBus)
   at COMETwebapp.SessionManagement.AuthenticationService.Login(AuthenticationDto authenticationDto)
   at COMETwebapp.Components.Login.ExecuteLogin()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
...
## System configuration
- COMET version:
  - [x ] COMET-WEB: 0.13.0
